<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="6691" started-at="2018-05-27T19:23:59Z" finished-at="2018-05-27T19:24:05Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="6691" started-at="2018-05-27T19:23:59Z" finished-at="2018-05-27T19:24:05Z">
      <class name="TestItemMaster">
        <test-method status="PASS" signature="testaddItem()[pri:0, instance:TestItemMaster@6d4b1c02]" name="testaddItem" duration-ms="47" started-at="2018-05-27T19:23:59Z" finished-at="2018-05-27T19:23:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testaddItem -->
        <test-method status="FAIL" signature="testdeleteItem()[pri:0, instance:TestItemMaster@6d4b1c02]" name="testdeleteItem" duration-ms="6503" started-at="2018-05-27T19:23:59Z" finished-at="2018-05-27T19:24:05Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[id to load is required for loading]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: id to load is required for loading
at org.hibernate.event.spi.LoadEvent.<init>(LoadEvent.java:93)
at org.hibernate.event.spi.LoadEvent.<init>(LoadEvent.java:63)
at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.doGetReference(SessionImpl.java:2718)
at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.getReference(SessionImpl.java:2700)
at org.hibernate.internal.SessionImpl.load(SessionImpl.java:1048)
at com.inventory.dao.ItemMasterDAO.delete(ItemMasterDAO.java:37)
at TestItemMaster.testdeleteItem(TestItemMaster.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testdeleteItem -->
      </class> <!-- TestItemMaster -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
